name: flappybird
channels: !!python/tuple
- !!python/unicode 'anaconda-fusion'
- !!python/unicode 'defaults'
dependencies:
- hdf5=1.8.17=1
- menpo::opencv3=3.1.0=py27_0
- menpo::tbb=4.3_20141023=0
- mkl=2017.0.1=0
- numpy=1.11.3=py27_0
- openssl=1.0.2k=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - funcsigs==1.0.2
  - mock==2.0.0
  - pbr==1.10.0
  - protobuf==3.2.0
  - pygame==1.9.3
  - six==1.10.0
  - tensorflow==0.12.1
prefix: /Users/patricia/anaconda2/envs/flappybird

